### ISSUE TITLE
CreateSchemaBackup Script - Add additional logic to drop the _Schema database after it gets backed up

### ISSUE THREAD

**Issue by csnhawkins** [HuxleyKendell/AutoRodent#1]
Simply put the below at the end of the script you have, then it become idempotent:

-- Drop Schema Database If Exists
DECLARE @DROP nvarchar(100);
DECLARE @RESULT NVARCHAR(200);
SET @DROP = 'DROP DATABASE IF EXISTS'
SET @RESULT = (@DROP+ ' '+@BackupDB)
EXEC sp_executesql @RESULT

**Comment by HuxleyKendell** [comment]
Works well! 
One issue is potentially that its fine writing multiple backups into the same file?

**Comment by HuxleyKendell** [comment]
May need peer review, but happy this works
